export const C = {
  primary: "#1A6FD1",
  primaryDark: "#1558A8",
  primaryLight: "#EFF6FF",
  bg: "#F1F5F9",
  card: "#FFFFFF",
  sidebar: "#0F172A",
  sidebarActive: "#1A6FD1",
  textDark: "#1E293B",
  textGray: "#64748B",
  textLight: "#94A3B8",
  border: "#E2E8F0",
  success: "#059669",
  warning: "#F59E0B",
  error: "#DC2626",
  purple: "#7C3AED",
  orange: "#EA580C",
};

export const navItems = [
  { key: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { section: "Academic" },
  { key: "students", label: "Students", icon: "GraduationCap" },
  { key: "teachers", label: "Teachers", icon: "Users" },
  { key: "classes", label: "Classes", icon: "School" },
  { section: "Attendance" },
  { key: "attendance", label: "Attendance", icon: "CheckSquare" },
  { section: "Content" },
  { key: "marks", label: "Marks & Reports", icon: "BarChart2" },
  { key: "videos", label: "Videos", icon: "Video" },
  { key: "sliders", label: "Slider Management", icon: "Image" },
  { section: "Communication" },
  { key: "notifications", label: "Notifications", icon: "Bell" },
  { section: "System" },
  { key: "appinfo", label: "App Info", icon: "Info" },
  { key: "settings", label: "Settings", icon: "Settings" },
];
